#!/bin/bash
export LTLD_LIBRARY_PATH=/opt/tme/lib
export LD_LIBRARY_PATH=/opt/tme/lib:/opt/tme/lib/tme
PATH=$PATH:/opt/tme/bin

tme-sun-idprom 3/150 8:0:20:11:22:33 > my-sun3-idprom.bin
tme-sun-eeprom < sun3-carrera-eeprom.txt > my-sun3-eeprom.bin
